
import Navbar from "@/components/Navbar";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="h-screen gap-5 flex flex-col">
        <Navbar/>
        <div className="px-8">
          {children}
        </div>
        
      </body>
    </html>
  );
}
