
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
      <AuthProvider>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      {children}
      </ThemeProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
